services:

  db:
    image: postgres:16.3-alpine3.20
    container_name: totem_db
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - totem_db:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: totem
    ports:
      - 5432:5432

volumes:
  totem_db:
